DjangoWeb/DjangoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('area.urls')),
]

DjangoWeb/area/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'area'
urlpatterns = [
    path('', views.login, name='login'),
    path('Home/', views.home, name='home'),
    path('client.apk', views.dlapk, name='home'),
    url(r'^Loader/', views.loading_page),
    url(r'^Register/', views.register),
    url(r'^Service/', views.service, name='service_connection'),
    url(r'^Page', views.page1),
]

DjangoWeb/area/models.py
from django.db import models

# Create your models here.

DjangoWeb/area/forms.py
from django import forms
import re 
class RegisterForm(forms.Form):
    def clean_email(self):
        email = self.cleaned_data['email']
        regex = '^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$'
        if(re.search(regex, email)):
            return email
        else:
            raise forms.ValidationError('Veuillez indiquer une adresse mail valide')

    userName = forms.CharField(label='Username', max_length=100, required=True)
    email = forms.EmailField(label='Email', max_length=100, required=True)
    telephone = forms.CharField(label='Telephone',  max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100, required=True)
    passwordVerif = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100, required=True)

class LoginForm(forms.Form):

    userName = forms.CharField(label='Username', max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100, required=True)

DjangoWeb/area/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.template import loader
from django.http import HttpResponse
import requests
from django.conf import settings
from django.conf.urls.static import static
from .forms import forms, RegisterForm, LoginForm
from django.core.files import File
from django.utils.encoding import smart_str

import requests

import os
import platform

# Create your views here.

def home(request):
    img_path = []
    if platform.system() == "Windows":
        path = settings.STATICFILES_DIRS[0] + "\\images" + "\\icon"
    else:
        path = settings.STATICFILES_DIRS[0] + "/images" + "/icon"
    # print("PATH = " + path)
    searchID = []
    for _, _, files in os.walk(path):
        img_path = files
        searchID.append(str(files).replace('-icon.png', ''))
    for index, elem in enumerate(img_path):
        if platform.system() == "Windows":
            img_path[index] += path + "\\" + elem
        else:
            print("PATH " + path + "/" + elem)
            img_path[index] = "/images/icon/" + elem
    # response = requests.get('https://area-rest-api-zuma.herokuapp.com/isonline')
    # geodata = response.text
    # print(searchID)
    # print(img_path)
    userToken = request.COOKIES.get('userToken')
    print(userToken)
    return render(request, 'index.html', {
        # 'ip': geodata,
        'img_path': img_path,
        'searchID': searchID,
        'nbOfImages': range(len(img_path)),
        'userToken': userToken
    })

def loading_page(request):
    return render(request, 'loader.html')

def login(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = request.POST.copy()
            userName = data.get('userName')
            password = data.get('password')
            url = 'https://area-rest-api-zuma.herokuapp.com/login'
            myobj = {
                'username': userName,
                'password': password
            }
            x = requests.post(url, data=myobj)
            if x.status_code == 400:
                form.add_error("password", forms.ValidationError((x.text)))
                return render(request, 'login_page.html', {
                    'form': form
                })
            else:
                response = redirect('/Home')
                response.set_cookie('userToken', x.headers['userToken'])
                return response
        else:
            return render(request, 'register_page.html', {
                'form': form
            })

    # if a GET (or any other method) we'll create a blank form
    else:
        form = LoginForm()
    return render(request, 'login_page.html', {
        'form': form
    })

def register(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            data = request.POST.copy()
            userName = data.get('userName')
            email = data.get('email')
            password = data.get('password')
            passwordVerif = data.get('passwordVerif')
            telephone = data.get('telephone')
            if password != passwordVerif:
                form.add_error(forms.ValidationError(('Les deux mots de passes ne sont pas identiques')))
            url = 'https://area-rest-api-zuma.herokuapp.com/register'
            myobj = {
                'username': userName,
                'password': password,
                'email': email,
                'telephone': telephone
            }
            x = requests.post(url, data = myobj)
            print(x.text)
            return redirect('/')
        else:
            return render(request, 'register_page.html', {
                'form': form
            })
    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegisterForm()
    return render(request, 'register_page.html', {
        'form': form
    })

def dlapk(request):
    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str('manga-rock-3-9-12-definitive.apk')
    response['X-Sendfile'] = smart_str(settings.STATICFILES_DIRS[0])
    return response

def service(request):
    return render(request, 'service_connection.html')

def page1(request):
    return render(request, 'page1.html')

DjangoWeb/area/templates/index.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <!-- <link href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="icon" type="image/png" href="{% static 'images/Logo/epitech-logo-signature-noir.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script> -->
    <!-- <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script> -->

    <title>Area</title>
</head>

<body>
    <header>
        <a href="{% url 'area:home' %}"><img class="logo" src="{% static 'images/Logo/Logo.png' %}" alt="logo"></a>
        <nav>
            <ul class="nav__links">
                <li><a onclick="searchFunction('cloud')">Cloud</a></li>
                <li><a onclick="searchFunction('mail')">Mail</a></li>
                <li><a onclick="searchFunction('message')">Message</a></li>
                <li><a onclick="searchFunction('socialNetwork')">Réseaux Sociaux</a></li>
                <li><a onclick="searchFunction('streaming')">Streaming</a></li>
            </ul>
        </nav>
        <div class="containerSearchBox">
            <input id="myInput" placeholder='Search...' class='js-search' type="text" onkeyup="searchFunction()">
            <i class="fa fa-search"></i>
        </div>
        <nav id="log-in">
            <ul class="nav__links">
                <li><a onclick="delete_cookie('userToken', '/', 'localhost')" href="/" id="disconnect">Se déconnecter</a></li>
            </ul>
        </nav>
        <!-- <div>
            <svg id="hamburger" viewBox="0 0 800 600">
                <path d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200" id="top">
                </path>
                <path d="M300,320 L540,320" id="middle"></path>
                <path d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190"
                    id="bottom" transform="translate(480, 320) scale(1, -1) translate(-480, -318) "></path>
            </svg>
        </div> -->
    </header>

    <div class="container">
    {% for image in img_path %}
        <div class="cards" id="{% static image %}">
            <div class="card_image"><a class="link_image" href="{% url 'area:service_connection' %}"><img src="{% static image %}" /></a></div>
            <div class="card_title title-white">
            </div>
        </div>
    {% endfor %}
    </div>
    <!-- {{ userToken }} -->
    <footer>
        <a href="https://www.epitech.eu/fr/"><img class="logo" src="{% static 'images/Logo/epitech-icon.png' %}" alt="logo"></a>
        <nav>
            <ul class="nav__links">
                <li><a href="https://www.linkedin.com/in/axel-terrand2018at/">Axel Terrand</a></li>
                <li><a href="https://twitter.com/ClmentDurand11">Clément Durand</a></li>
                <li><a href="https://www.linkedin.com/in/matthieu-correiam/">Matthieu Correia Moreira</a></li>
                <li><a href="https://www.linkedin.com/in/tom-robert-800763155/">Tom Robert</a></li>
                <li><a href="https://www.linkedin.com/in/souhib-trabelsi-2492a5163/">Souhib Trabelsi</a></li>
            </ul>
        </nav>
        <nav id="log-in">
            <ul class="nav__links">
                <a href="{% url 'area:home' %}"><img class="logo" src="{% static 'images/Logo/Logo.png' %}" alt="logo"></a>
                <!-- <li><a href="#">Se déconnecter</a></li> -->
            </ul>
        </nav>
    </footer>
</body>

<!-- <script src="{% static 'js/hamburger.js' %}"></script> -->
<script src="{% static 'js/searchbar.js' %}"></script>
<!-- <script src="{% static 'js/handleAuth.js' %}"></script> -->
</html>

DjangoWeb/area/templates/loader.html
<html>
    <head>
        <meta http-equiv="refresh" content="1;url=http://127.0.0.1:8000/Home/" />
    </head>
    <body>
        <style>
            
    .loader{
    border:5px solid;
    width:100px;
    height:100px;
    border-radius:50%;
    border-color:orange transparent transparent;
    animation:spin 1s linear infinite;
    position:fixed;
    top:0;
    bottom:0;
    left:0;
    right:0;
    margin:auto;
  }

  @keyframes spin{
    100%{transform:rotate(360deg);filter:hue-rotate(360deg)}
  }

  body{

    min-height: 100vh;
    background-image: linear-gradient(120deg, #0F2027, #203A43, #2c5364);
}
        </style>
        <div class="loader"></div>
    </body>
</html>

DjangoWeb/area/templates/login_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <link rel="stylesheet" href="#style.css"> -->
    {% load static %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login_page.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/Logo/epitech-logo-signature-noir.png' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>

  </head>
  <body>

      <form method="POST" class="login-form">
        {% csrf_token %}

  <h1>Login</h1>


  <div class="txt">
    <!-- <input type="mail"> -->
    {{ form.userName }}
    <span data-placeholder="Username"></span>
    </div>
  <div class="txt">
    <!-- <input type="Password"> -->
    {{ form.password }}
    <span data-placeholder="Password"></span>
  </div>

  <div class="bottom-text">
    <h2>Don't have account? <a href="Register">Sign up</a></h2>
    </div>

    <input type="submit" class="button" value="Submit">
    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
  {% endif %}


</form>

<script src="{% static 'js/login_page.js' %}"></script>

  </body>
</html>

DjangoWeb/area/templates/page1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/page1.css' %}">
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <title>Document</title>
</head>

<body>

  <div class="bg"></div>
  <div class="bg bg2"></div>
  <div class="bg bg3"></div>

  <input type="button" class="Main_text" id="main_text"/>

  <label class="switch">
    <input type="checkbox" class="checkbox" id="toggleSwitch" onclick="doOnClick();" />
    <div class=""></div>

  </label>
  <input type="button" class="Switch_Text" value="Disconnected" id="switch_text" disabled/>

  <!-- <script src="{% static 'js/auth.js' %}"></script> -->
</body>
<script type="text/javascript" src="{% static 'js/page1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/handleAuthSecondParam.js' %}"></script>
</html>

DjangoWeb/area/templates/register_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <title>Register</title>
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
      <link rel="stylesheet" href="https://kit.fontawesome.com/c609fbac99.js" crossorigin="anonymous">
      <link rel="icon" type="image/png" href="{% static 'images/Logo/epitech-logo-signature-noir.png' %}" />
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"/>
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"/>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>
  </head>
  <body>
      <form class="login-form" method="post">
        {% csrf_token %}
        <h1>Register</h1>

        <div class="txtb">
          {{ form.userName }}
          <span data-placeholder="Username"></span>
        </div>

        <div class="txtb">
          {{ form.email }}
          <span data-placeholder="Email"></span>
        </div>

        <div class="txtb">
          {{ form.telephone }}
          <span data-placeholder="Telephone"></span>
        </div>

        <div class="txtb">
          {{ form.password }}
          <span data-placeholder="Password"></span>
        </div>

        <div class="txtb">
          {{ form.passwordVerif }}
          <span data-placeholder="Password Verification"></span>
        </div>

        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
        {% endif %}

        <input type="submit" class="logbtn" value="Register" href="/">

      </form>
    
    <script src="{% static 'js/register.js' %}"></script>
  </body>
</html>

DjangoWeb/area/templates/service_connection.html
<!DOCTYPE html>
<html>
  <head>
    <title>Services</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/service_connection.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/Logo/epitech-logo-signature-noir.png' %}" />
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- <script src="{% static 'js/Service_connection.js' %}"></script> -->
  </head>

<body>
<div class="image">
<img src="/static/images/icon/amazon-icon.png">
</div>
<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div class="w3-container buttons">
  <!-- <p><button class="w3-button w3-black" onclick="window.location.href='/Page?Add_Calendar_Alert'" id="button1" >Add Calendar Alert</button></p>
  <p><button class="w3-button w3-black" onclick="window.location.href='/Page?Add_new_music'" id="button2">Add new music</button></p> -->

</div>

<script type="text/javascript" src="{% static 'js/handleAuth.js' %}"></script>
<script type="text/javascript" src="{% static 'js/service_connection.js' %}"></script>
</body>